/* PASALO CARS PH — MARKETPLACE LISTINGS */
(function(){'use strict';
var allVehicles=[],filteredVehicles=[];
function money(n,f){f=f||'PM for details';if(n==null||n===''||Number.isNaN(Number(n)))return f;return '₱'+Number(n).toLocaleString('en-PH')}
function show(v){return v==null||v===''?'To confirm':String(v)}
function title(v){return [v.year,v.make,v.model,v.variant&&v.variant!=='—'?v.variant:''].filter(Boolean).join(' ')}
function age(v){if(!v.listedAt)return'Listed recently';var t=new Date(v.listedAt).getTime();if(!Number.isFinite(t))return'Listed recently';var h=Math.max(0,(Date.now()-t)/36e5);if(h<1)return'Listed '+Math.max(1,Math.round(h*60))+' min ago';if(h<24)return'Listed '+Math.round(h)+' hr ago';var d=Math.round(h/24);return'Listed '+d+' day'+(d===1?'':'s')+' ago'}
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;')}
function num(v){if(v==null||v==='')return null;var n=Number(String(v).replace(/[^0-9.-]/g,''));return Number.isNaN(n)?null:n}
function imgUrl(p){if(!p)return'';if(/^https?:\/\//i.test(p))return p;return new URL(String(p).replace(/^\.\//,''),document.baseURI).href}
function normalize(v){if(!v||typeof v!=='object')return v;if(v.monthly==null&&v.monthly_payment!=null)v.monthly=v.monthly_payment;if(v.cashOut==null&&v.cash_out!=null)v.cashOut=v.cash_out;if(v.monthsRemaining==null&&v.remaining_months!=null)v.monthsRemaining=v.remaining_months;if(v.mileage==null&&v.odometer!=null)v.mileage=String(v.odometer)+(v.odometer_unit?' '+v.odometer_unit:'');if(v.bank==null&&v.financing!=null)v.bank=v.financing;if(!v.nextDue&&v.due_date)v.nextDue=v.due_date;if(!v.bodyType)v.bodyType='Vehicle';if(!v.status)v.status='active';return v}
function card(v){var t=title(v),u=imgUrl(v.image),cash=num(v.cashOut),inq='https://m.me/PasaloCarsPH21?ref='+encodeURIComponent('Marketplace inquiry: '+t);var image=u?'<img src="'+esc(u)+'" alt="'+esc(t)+'" loading="lazy" decoding="async" onerror="this.remove()">':'<div class="vehicle-image-fallback">'+esc(v.emoji||'🚗')+'</div>';return '<article class="vehicle-card"><div class="vehicle-image">'+image+(v.color?'<div class="vehicle-badges"><span class="badge">'+esc(v.color)+'</span></div>':'')+'</div><div class="vehicle-body"><div class="vehicle-title">'+esc(t)+'</div><div class="vehicle-price">'+(cash!=null?money(cash):'PM')+' cash-out</div><div class="vehicle-monthly">'+money(v.monthly)+(v.monthly!=null?' / month':'')+'</div><div class="vehicle-meta"><span>📍 '+esc(show(v.location))+'</span><span>🏦 '+esc(show(v.bank))+'</span><span>'+esc(age(v))+'</span></div><div class="vehicle-actions"><a class="btn btn-secondary" href="vehicle.html?id='+encodeURIComponent(v.id)+'">View Details</a><a class="btn btn-primary" target="_blank" rel="noopener" href="'+esc(inq)+'">💬 Inquire</a></div></div></article>'}
function filters(){var makes=new Set(),locs=new Set(),bodies=new Set();allVehicles.forEach(function(v){if(v.make)makes.add(v.make);if(v.location&&v.location!=='To confirm')locs.add(v.location);if(v.bodyType)bodies.add(v.bodyType)});function fill(id,set,label){var e=document.getElementById(id);if(!e)return;var cur=e.value;e.innerHTML='<option value="">'+label+'</option>';Array.from(set).sort().forEach(function(x){var o=document.createElement('option');o.value=x;o.textContent=x;e.appendChild(o)});if(cur)e.value=cur}fill('make',makes,'Any brand');fill('location',locs,'Any location');fill('body',bodies,'Any type')}
function apply(){var q=(document.getElementById('q')?.value||'').trim().toLowerCase(),make=document.getElementById('make')?.value||'',loc=document.getElementById('location')?.value||'',body=document.getElementById('body')?.value||'',mxm=num(document.getElementById('monthly')?.value),mxc=num(document.getElementById('cash')?.value),minm=num(document.getElementById('min-monthly')?.value),minc=num(document.getElementById('min-cash')?.value),sort=document.getElementById('sort')?.value||'new';filteredVehicles=allVehicles.filter(function(v){if(v.status!=='active')return false;var s=[v.year,v.make,v.model,v.variant,v.color,v.location].join(' ').toLowerCase();if(q&&!s.includes(q))return false;if(make&&v.make!==make)return false;if(loc&&v.location!==loc)return false;if(body&&v.bodyType!==body)return false;var m=num(v.monthly),c=num(v.cashOut);if(m!=null&&mxm!=null&&m>mxm)return false;if(m!=null&&minm!=null&&m<minm)return false;if(c!=null&&mxc!=null&&c>mxc)return false;if(c!=null&&minc!=null&&c<minc)return false;return true});if(sort==='monthly')filteredVehicles.sort((a,b)=>(num(a.monthly)??Infinity)-(num(b.monthly)??Infinity));else if(sort==='cash')filteredVehicles.sort((a,b)=>(num(a.cashOut)??Infinity)-(num(b.cashOut)??Infinity));else if(sort==='year')filteredVehicles.sort((a,b)=>(b.year||0)-(a.year||0));else filteredVehicles.sort((a,b)=>new Date(b.listedAt||0)-new Date(a.listedAt||0));render()}
function render(){var g=document.getElementById('results-grid');if(!g)return;var c=document.getElementById('result-count'),s=document.getElementById('result-summary');if(c)c.textContent=filteredVehicles.length+' vehicle'+(filteredVehicles.length===1?'':'s')+' found';if(s)s.textContent=filteredVehicles.length?'Showing latest listings':'No matches found';g.innerHTML=filteredVehicles.length?filteredVehicles.map(card).join(''):'<div class="empty">No vehicles match those filters yet. Try a wider budget or location.</div>';if(typeof window.updateMarketplaceCTAs==='function')window.updateMarketplaceCTAs()}
function clear(){['q','make','location','body','monthly','cash','min-monthly','min-cash'].forEach(function(id){var e=document.getElementById(id);if(e)e.value=''});var s=document.getElementById('sort');if(s)s.value='new';apply()}
function repair(text){return text.replace(/("cash_out"\s*:\s*-?\d+(?:\.\d+)?)"(?=\s*[,}\n])/g,'$1').replace(/("monthly_payment"\s*:\s*-?\d+(?:\.\d+)?)"(?=\s*[,}\n])/g,'$1').replace(/("remaining_months"\s*:\s*-?\d+(?:\.\d+)?)"(?=\s*[,}\n])/g,'$1')}
async function get(url){var ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),10000);try{var r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json'},signal:ctl.signal});if(!r.ok)throw Error('HTTP '+r.status);var text=await r.text();try{return JSON.parse(text)}catch(e){return JSON.parse(repair(text))}}finally{clearTimeout(timer)}}
async function load(){var g=document.getElementById('results-grid');if(g)g.innerHTML='<div class="empty">Loading marketplace...</div>';var stamp=Date.now(),sources=[new URL('data/vehicles.json?v='+stamp,document.baseURI).href,'https://raw.githubusercontent.com/Pasalo-Cars-PH/Pasalo-Assumed-Balance-Marketplace/v1-marketplace/data/vehicles.json?v='+stamp];var err;for(var i=0;i<sources.length;i++)try{var d=await get(sources[i]);var list=Array.isArray(d.vehicles)?d.vehicles.map(normalize):[];if(!list.length)throw Error('Vehicle data is empty');allVehicles=list;window.vehicles=allVehicles;filters();apply();console.log('Marketplace loaded',list.length);return}catch(e){err=e;console.warn('Data source failed',sources[i],e)}console.error('Marketplace failed',err);if(g)g.innerHTML='<div class="empty"><b>Marketplace data could not be loaded.</b><br><button type="button" class="btn btn-secondary" id="retry-listings" style="margin-top:12px">Retry</button></div>';document.getElementById('retry-listings')?.addEventListener('click',load)}
window.renderListings=apply;document.addEventListener('DOMContentLoaded',function(){if(!document.getElementById('results-grid'))return;document.getElementById('apply')?.addEventListener('click',apply);document.getElementById('clear-filters')?.addEventListener('click',clear);document.getElementById('sort')?.addEventListener('change',apply);document.getElementById('q')?.addEventListener('input',function(){clearTimeout(window._searchTimer);window._searchTimer=setTimeout(apply,250)});load()});
})();